//
//  RemoteRecipeSource.swift
//  WhiskyKit
//
//  This file is part of Whisky.
//
//  Whisky is free software: you can redistribute it and/or modify it under the terms
//  of the GNU General Public License as published by the Free Software Foundation,
//  either version 3 of the License, or (at your option) any later version.
//
//  Whisky is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//  See the GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with Whisky.
//  If not, see https://www.gnu.org/licenses/.
//

import Foundation
import os.log

// MARK: - Wire types

/// Manifest that enumerates every recipe the remote repository is
/// publishing. The manifest lives at a stable path so the client can
/// fetch it with a single request and learn the full set without
/// directory-listing (which GitHub raw CDN does not support).
///
/// Regenerated by `.github/workflows/RecipeIndex.yml` when `main` changes
/// so the manifest is never out of sync with the actual recipe files.
public struct RecipeIndex: Codable, Sendable, Equatable {
    public let schema: Int
    /// ISO-8601 UTC timestamp of the generator run.
    public let generatedAt: String
    /// Every recipe in the `Recipes/` tree, each with the sha of its blob
    /// so the client can skip redownloading unchanged files.
    public let recipes: [Entry]

    public struct Entry: Codable, Sendable, Equatable, Hashable {
        public let id: String
        /// Path under `WhiskyKit/Sources/WhiskyKit/Recipes/`, e.g.
        /// `steam/2050650.json`. The client joins this with the raw CDN
        /// base URL to download the file.
        public let path: String
        /// Git blob sha of the file. Stable key for "did this file
        /// change" questions. 40 hex chars.
        public let sha: String
        /// File size in bytes, for progress bars.
        public let size: Int

        public init(id: String, path: String, sha: String, size: Int) {
            self.id = id
            self.path = path
            self.sha = sha
            self.size = size
        }
    }

    public init(schema: Int = 1, generatedAt: String, recipes: [Entry]) {
        self.schema = schema
        self.generatedAt = generatedAt
        self.recipes = recipes
    }

    enum CodingKeys: String, CodingKey {
        case schema
        case generatedAt = "generated_at"
        case recipes
    }
}

// MARK: - Errors

public enum RemoteRecipeError: Error, LocalizedError {
    case indexUnreachable(underlying: Error)
    case indexMalformed(underlying: Error)
    case recipeUnreachable(id: String, underlying: Error)
    case recipeMalformed(id: String, underlying: Error)
    case notModified

    public var errorDescription: String? {
        switch self {
        case .indexUnreachable(let err):
            return "Could not reach the recipe index: \(err.localizedDescription)"
        case .indexMalformed(let err):
            return "Recipe index was unreadable: \(err.localizedDescription)"
        case .recipeUnreachable(let id, let err):
            return "Could not fetch recipe \(id): \(err.localizedDescription)"
        case .recipeMalformed(let id, let err):
            return "Recipe \(id) was unreadable: \(err.localizedDescription)"
        case .notModified:
            return "Recipe index has not changed."
        }
    }
}

// MARK: - Source

/// Fetches the recipe index and individual recipes from the MacBottle
/// GitHub repository via the public raw.githubusercontent.com CDN.
///
/// This type is intentionally stateless: all caching state (ETag, last
/// known index) lives in `RecipeCache`, which this type takes as a
/// dependency so tests can inject an in-memory stub. The network layer is
/// abstracted behind a `DataFetcher` closure so tests can feed canned
/// responses without standing up a real HTTP server.
public final class RemoteRecipeSource: Sendable {
    /// Default branch and path layout match the live MacBottle repo.
    public struct Configuration: Sendable {
        public let owner: String
        public let repo: String
        public let branch: String
        public let recipesRootPath: String
        public let indexPath: String

        public init(
            owner: String = "shiahonb777",
            repo: String = "MacBottle",
            branch: String = "main",
            recipesRootPath: String = "WhiskyKit/Sources/WhiskyKit/Recipes",
            indexPath: String = "WhiskyKit/Sources/WhiskyKit/Recipes/_index.json"
        ) {
            self.owner = owner
            self.repo = repo
            self.branch = branch
            self.recipesRootPath = recipesRootPath
            self.indexPath = indexPath
        }

        /// `https://raw.githubusercontent.com/<owner>/<repo>/<branch>/`
        public var rawBaseURL: URL {
            // swiftlint:disable:next force_unwrapping
            URL(string: "https://raw.githubusercontent.com/\(owner)/\(repo)/\(branch)/")!
        }

        public var indexURL: URL {
            rawBaseURL.appending(path: indexPath)
        }

        public func recipeURL(for path: String) -> URL {
            rawBaseURL.appending(path: "\(recipesRootPath)/\(path)")
        }
    }

    /// Network indirection so tests can inject fixture responses without
    /// a live URLSession. Returns `(data, etag)` on success.
    public typealias DataFetcher = @Sendable (
        _ url: URL, _ ifNoneMatch: String?
    ) async throws -> (Data, String?)

    public let configuration: Configuration
    private let fetcher: DataFetcher

    public init(
        configuration: Configuration = Configuration(),
        fetcher: DataFetcher? = nil
    ) {
        self.configuration = configuration
        self.fetcher = fetcher ?? Self.defaultFetcher
    }

    /// Fetch the remote index. Pass the previously stored ETag to enable
    /// conditional GET; on a 304 the call throws `.notModified` so the
    /// caller can keep using cached data.
    public func fetchIndex(previousETag: String? = nil) async throws -> (RecipeIndex, String?) {
        let data: Data
        let etag: String?
        do {
            (data, etag) = try await fetcher(configuration.indexURL, previousETag)
        } catch RemoteRecipeError.notModified {
            throw RemoteRecipeError.notModified
        } catch {
            throw RemoteRecipeError.indexUnreachable(underlying: error)
        }

        do {
            let index = try JSONDecoder().decode(RecipeIndex.self, from: data)
            return (index, etag)
        } catch {
            throw RemoteRecipeError.indexMalformed(underlying: error)
        }
    }

    /// Fetch a single recipe file identified by its index entry. The sha
    /// is not verified against the downloaded bytes here; `RecipeCache`
    /// is the right place to enforce integrity if we ever need it.
    public func fetchRecipe(_ entry: RecipeIndex.Entry) async throws -> Recipe {
        let url = configuration.recipeURL(for: entry.path)
        let data: Data
        do {
            (data, _) = try await fetcher(url, nil)
        } catch {
            throw RemoteRecipeError.recipeUnreachable(id: entry.id, underlying: error)
        }

        do {
            return try JSONDecoder().decode(Recipe.self, from: data)
        } catch {
            throw RemoteRecipeError.recipeMalformed(id: entry.id, underlying: error)
        }
    }

    // MARK: - Default URLSession-backed fetcher

    @Sendable
    private static func defaultFetcher(
        url: URL, ifNoneMatch: String?
    ) async throws -> (Data, String?) {
        var request = URLRequest(url: url)
        request.cachePolicy = .reloadIgnoringLocalCacheData
        if let ifNoneMatch {
            request.setValue(ifNoneMatch, forHTTPHeaderField: "If-None-Match")
        }

        let session = URLSession(configuration: .ephemeral)
        let (data, response) = try await session.data(for: request)

        guard let http = response as? HTTPURLResponse else {
            return (data, nil)
        }
        if http.statusCode == 304 {
            throw RemoteRecipeError.notModified
        }
        guard (200..<300).contains(http.statusCode) else {
            let err = NSError(
                domain: "RemoteRecipeSource", code: http.statusCode,
                userInfo: [NSLocalizedDescriptionKey: "HTTP \(http.statusCode)"]
            )
            throw err
        }
        let etag = http.value(forHTTPHeaderField: "ETag")
        Logger.wineKit.debug("MacBottle: fetched \(url.lastPathComponent), etag=\(etag ?? "none")")
        return (data, etag)
    }
}
